/* empty css                      */import{a as b,S as R,i as a}from"./assets/vendor-BtI-3F0k.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const q="4823621-792051e21e56534e6ae2e472f";b.defaults.baseURL="https://pixabay.com/api/";async function L(e,r=1,i=40){const o={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i};return(await b.get("",{params:o})).data}const A=document.querySelector("#search-form"),h=document.querySelector(".gallery"),y=document.querySelector(".load-more"),l=document.querySelectorAll(".loader-container");let w=new R(".gallery a",{captionsData:"alt",captionDelay:250}),m="",n=1,u=0,d=0;const g=40,P=3;A.addEventListener("submit",E);y.addEventListener("click",$);async function E(e){e.preventDefault();const r=e.currentTarget,i=r.elements.searchQuery.value.trim();if(i===""){a.warning({message:"Please enter a search keyword!",position:"topRight"});return}m=i,n=1,d=0,h.innerHTML="",f(),S(l[0]);try{const o=await L(m,n,g);if(o.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p(l[0]);return}u=o.totalHits,d=o.hits.length;const t=v(o.hits);h.innerHTML=t,w.refresh(),d<u&&n<P?H():(f(),u>0&&a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.error(o),a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p(l[0]),r.reset()}}async function $(){n+=1,S(l[1]);try{const e=await L(m,n,g);if(e.hits.length===0){n-=1,f(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}d+=e.hits.length;const r=v(e.hits);h.insertAdjacentHTML("beforeend",r),w.refresh(),(d>=u||e.hits.length<g||n>=P)&&(f(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),O()}catch(e){console.error(e),a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p(l[1])}}function v(e){return e.map(({webformatURL:r,largeImageURL:i,tags:o,likes:t,views:s,comments:c,downloads:M})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${r}" alt="${o}" />
      </a>
      <div class="info-box">
        <p class="info-item"><b>Likes</b><br>${t}</p>
        <p class="info-item"><b>Views</b><br>${s}</p>
        <p class="info-item"><b>Comments</b><br>${c}</p>
        <p class="info-item"><b>Downloads</b><br>${M}</p>
      </div>
    </li>
  `).join("")}function S(e){e.classList.remove("is-hidden")}function p(e){e.classList.add("is-hidden")}function H(){y.classList.remove("is-hidden")}function f(){y.classList.add("is-hidden")}function O(){const e=h.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
