/* empty css                      */import{a as g,S as v,i as c}from"./assets/vendor-BtI-3F0k.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const M="56323626-86daf2d15d21cca2bf86958bc";g.defaults.baseURL="https://pixabay.com/api/";async function y(t,r=1,a=40){const s={key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a};return(await g.get("",{params:s})).data}const q=document.querySelector("#search-form"),d=document.querySelector(".gallery"),p=document.querySelector(".load-more"),l=document.querySelectorAll(".loader-container");let b=new v(".gallery a",{captionsData:"alt",captionDelay:250}),f="",i=1,m=0;const u=40;q.addEventListener("submit",R);p.addEventListener("click",$);async function R(t){t.preventDefault();const r=t.currentTarget,a=r.elements.searchQuery.value.trim();if(a===""){c.warning({message:"Please enter a search keyword!",position:"topRight"});return}f=a,i=1,d.innerHTML="",P(),w(l[0]);try{const s=await y(f,i,u);if(s.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),h(l[0]);return}m=s.totalHits;const e=L(s.hits);d.innerHTML=e,b.refresh(),i*u<m&&E()}catch(s){console.error(s),c.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h(l[0]),r.reset()}}async function $(){i+=1,w(l[1]);try{const t=await y(f,i,u),r=L(t.hits);d.insertAdjacentHTML("beforeend",r),b.refresh(),i*u>=m&&(P(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),H()}catch(t){console.error(t),c.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h(l[1])}}function L(t){return t.map(({webformatURL:r,largeImageURL:a,tags:s,likes:e,views:o,comments:n,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${r}" alt="${s}" />
      </a>
      <div class="info-box">
        <p class="info-item"><b>Likes</b><br>${e}</p>
        <p class="info-item"><b>Views</b><br>${o}</p>
        <p class="info-item"><b>Comments</b><br>${n}</p>
        <p class="info-item"><b>Downloads</b><br>${S}</p>
      </div>
    </li>
  `).join("")}function w(t){t.classList.remove("is-hidden")}function h(t){t.classList.add("is-hidden")}function E(){p.classList.remove("is-hidden")}function P(){p.classList.add("is-hidden")}function H(){const t=d.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
